project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"

freeze: true

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Tyler Burleigh"
description-meta: "Tyler Burleigh is a Senior Data Scientist at Prodigy education trying to make math education more fun."
author-meta: "Tyler Burleigh"

website:
  title: "Tyler Burleigh"
  description: "{{< meta description-meta >}}"
  favicon: "/files/favicon-512.png"
  site-url: "https://tylerburleigh.com"
  repo-url: "https://github.com/tylerburleigh/tylerburleigh-ath-quarto"

  google-analytics: "G-PRHQZ8HPLB"
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Research"
        file: research/index.qmd
    
    right:
      - icon: mastodon
        aria-label: mastodon
        href: https://fosstodon.org/@tylerburleigh
        rel: me
      - icon: github
        aria-label: github
        href: https://github.com/tylerburleigh
        rel: me
      - icon: linkedin
        aria-label: linkedin
        href: https://www.linkedin.com/in/tylerburleigh
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Tyler Burleigh</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">Based on [ath-quarto](https://github.com/andrewheiss/ath-quarto) by [Andrew Heiss](https://www.andrewheiss.com)</span>

format:
  html:
    theme: 
      - html/ath.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
